#!/bin/bash

CERTFILE=$(tmsh run sys crypto check-cert | grep 'expired on' | grep -E 'CIS|CUST|fqdn' | awk -F '/' '{ print $3}' | awk -F ' ' '{ print $1}' 2> /dev/null | uniq)
tmsh list /ltm profile one-line > 1_profiles.txt
FILE=1_profiles.txt
echo "__________________________________________________________"

for VAR in ${CERTFILE}
do
  grep -q "$VAR" "$FILE"
  if [[ $? != 0 ]]
  then
    echo "${VAR}"
  fi
done
rm -rf 1_profiles.txt
